# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-TT2
version:      0.03
version_from: 
installdirs:  site
requires:
    CGI::Builder:                  1.12
    Scalar::Util:                  0
    Template:                      2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
